name: 'ml_on_fhir'

config-version: 2
version: '0.1.0'
profile: 'ml_on_fhir'
require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  fhirschema: fhir
  # 230690007 - Stroke
  target-code: 230690007
  minimal-age: 30
  target-years: 30

models:
  ml_on_fhir:
    last:
      +materialized: table
    pivot:
      +materialized: table
    mlready:
      +materialized: view

seeds:
  ml_on_fhir:
    synthea-lc-dataset-codes:
      +column_types:
        code: varchar(20)
        name: varchar(1000)
      alias: synthea_lc_codes
    synthea-stroke-dataset-codes:
      +column_types:
        code: varchar(20)
        name: varchar(1000)
      alias: synthea_stroke_codes
