name: 'ml_on_fhir'

config-version: 2
version: '0.1.0'
profile: 'ml_on_fhir'
require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  fhirschema: fhir

  target: lung-cancer
  minimal-age: 30
  target-years: 40
  target-horizon-months: 12

  split-test-pct: 20
  split-train-pct: 80
  split-seed: 1234

  stroke:
    codes: 
      - 230690007
    codes-dataset: synthea-stroke-dataset-codes
    lhs-dataset: lhs-stroke-ml-codes

  lung-cancer:
    codes: 
      - 162573006
      - 254637007
      - 424132000
    codes-dataset: synthea-lc-dataset-codes
    lhs-dataset: lhs-lc-ml-codes

models:
  ml_on_fhir:
    last:
      +materialized: table
    pivot:
      +materialized: table
    mlready:
      +materialized: table

seeds:
  ml_on_fhir:
    synthea-lc-dataset-codes:
      +full_refresh: true
      +column_types:
        code: varchar(20)
        name: varchar(1000)
      +alias: synthea_lc_codes
      indexes:
        - name: codeidx
          columns: 
            - code
          data:
            - name
    synthea-stroke-dataset-codes:
      +full_refresh: true
      +column_types:
        code: varchar(20)
        name: varchar(1000)
      +alias: synthea_stroke_codes
      indexes:
        - name: codeidx
          columns: 
            - code
          data:
            - name
