version: '3.7'
services:
  iris: 
    env_file: .env
    build: 
      context: .
      args:
        - IMAGE=containers.intersystems.com/intersystems/irishealth-ml:2023.1.0.229.0
    restart: unless-stopped
    ports:
      - 33782:1972
      - 33783:52773
      - 33784:53773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./init.db/:/docker-entrypoint-initdb.d/
      - ./:/home/irisowner/ml-on-fhir/
      - ./FHIRSERVERX0001R:/usr/irissys/mgr/FHIRSERVERX0001R
      - irissyslib:/usr/irissys/lib
      - irissys:/usr/irissys
    # working_dir: /home/irisowner/ml-on-fhir

  synthea:
    profiles:
      - cli
    build: 
      context: .
      dockerfile: Dockerfile-synthea
    command: [ "bash" ]
    volumes:
      - ./data/fhir:/output
  
  superset:
    env_file: .env
    depends_on:
      - iris
      - redis
      - db
    build: 
      context: superset
    ports:
      - 8088:8088
    restart: unless-stopped
  
  db:
    env_file: .env
    image: postgres:14
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data

  redis:
    image: redis:7    
    restart: unless-stopped
    volumes:
      - redis:/data

  notebook:
    build: 
      context: notebook
      dockerfile: dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./notebook/Notebooks:/Notebooks
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/Notebooks"

volumes:
  irissys: 
  irissyslib: 
  redis:
  db_home:
